#ifndef LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_H
#define LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_H

typedef struct yc_res_map_level_object_patch_item {
    yc_res_pro_object_item_type_t type;
} yc_res_map_level_object_patch_item_t;

#endif //LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_H
