#ifndef LIB_YCRES_PRO_TYPES_COMMON_SKILL_H
#define LIB_YCRES_PRO_TYPES_COMMON_SKILL_H

typedef enum yc_res_pro_skill {
    YC_RES_PRO_SKILL_SMALL_GUNS,
    YC_RES_PRO_SKILL_BIG_GUNS,
    YC_RES_PRO_SKILL_ENERGY_WEAPONS,
    YC_RES_PRO_SKILL_UNARMED,
    YC_RES_PRO_SKILL_MELEE_WEAPONS,
    YC_RES_PRO_SKILL_THROWING,
    YC_RES_PRO_SKILL_FIRST_AID,
    YC_RES_PRO_SKILL_DOCTOR,
    YC_RES_PRO_SKILL_SNEAK,
    YC_RES_PRO_SKILL_LOCK_PICK,
    YC_RES_PRO_SKILL_STEAL,
    YC_RES_PRO_SKILL_TRAPS,
    YC_RES_PRO_SKILL_SCIENCE,
    YC_RES_PRO_SKILL_REPAIR,
    YC_RES_PRO_SKILL_SPEECH,
    YC_RES_PRO_SKILL_BARTER,
    YC_RES_PRO_SKILL_GAMBLING,
    YC_RES_PRO_SKILL_OUTDOORS_MAN,
    YC_RES_PRO_SKILL_COUNT
} yc_res_pro_skill_t;

#endif //LIB_YCRES_PRO_TYPES_COMMON_SKILL_H
