#ifndef LIBYCRES_INCLUDE_PRO_STATUSES_H
#define LIBYCRES_INCLUDE_PRO_STATUSES_H

typedef enum yc_res_pro_status {
    YC_RES_PRO_STATUS_OK = 0,
    YC_RES_PRO_STATUS_IO,
    YC_RES_PRO_STATUS_MEM,
    YC_RES_PRO_STATUS_CORR,
} yc_res_pro_status_t;

#endif //LIBYCRES_INCLUDE_PRO_STATUSES_H
