#ifndef LIB_YCRES_PRO_TYPES_SCRIPT_H
#define LIB_YCRES_PRO_TYPES_SCRIPT_H

typedef enum yc_res_pro_script_type {
    YC_RES_PRO_SCRIPT_TYPE_SPATIAL = 1,
    YC_RES_PRO_SCRIPT_TYPE_ITEM,
    YC_RES_PRO_SCRIPT_TYPE_SCENERY,
    YC_RES_PRO_SCRIPT_TYPE_CRITTER,
} yc_res_pro_script_type_t;

#endif //LIB_YCRES_PRO_TYPES_SCRIPT_H
