#ifndef LIB_YCRES_PRO_TYPES_SCRIPT_H
#define LIB_YCRES_PRO_TYPES_SCRIPT_H

typedef enum yc_res_pro_script_type {
    YC_RES_PRO_SCRIPT_TYPE_SYSTEM,
    YC_RES_PRO_SCRIPT_TYPE_SPATIAL,
    YC_RES_PRO_SCRIPT_TYPE_TIMED,
    YC_RES_PRO_SCRIPT_TYPE_ITEM,
    YC_RES_PRO_SCRIPT_TYPE_CRITTER,
    YC_RES_PRO_SCRIPT_TYPE_COUNT,
} yc_res_pro_script_type_t;

#endif //LIB_YCRES_PRO_TYPES_SCRIPT_H
