#ifndef LIB_YCRES_PRO_TYPES_COMMON_DAMAGE_H
#define LIB_YCRES_PRO_TYPES_COMMON_DAMAGE_H

typedef enum yc_res_pro_types_damage {
    YC_RES_PRO_DAMAGE_NORMAL,
    YC_RES_PRO_DAMAGE_LASER,
    YC_RES_PRO_DAMAGE_FIRE,
    YC_RES_PRO_DAMAGE_PLASMA,
    YC_RES_PRO_DAMAGE_ELECTRICAL,
    YC_RES_PRO_DAMAGE_EMP,
    YC_RES_PRO_DAMAGE_EXPLOSION,
    YC_RES_PRO_DAMAGE_COUNT
} yc_res_pro_types_damage_t;

#endif //LIB_YCRES_PRO_TYPES_COMMON_DAMAGE_H
