#ifndef INCLUDE_PRO_TYPES_COMMON_MATERIAL_H
#define INCLUDE_PRO_TYPES_COMMON_MATERIAL_H

typedef enum yc_res_pro_material {
    YC_RES_MATERIAL_GLASS = 0,
    YC_RES_MATERIAL_METAL,
    YC_RES_MATERIAL_PLASTIC,
    YC_RES_MATERIAL_WOOD,
    YC_RES_MATERIAL_DIRT,
    YC_RES_MATERIAL_STONE,
    YC_RES_MATERIAL_CEMENT,
    YC_RES_MATERIAL_LEATHER,
} yc_res_pro_material_t;

#endif //INCLUDE_PRO_TYPES_COMMON_MATERIAL_H
