#ifndef LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_KEY_H
#define LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_KEY_H

typedef struct yc_res_map_level_object_patch_item_key {
    uint32_t code;
} yc_res_map_level_object_patch_item_key_t;

#endif //LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_KEY_H
