#ifndef LIBYCRES_INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_KEY_H
#define LIBYCRES_INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_KEY_H

typedef struct yc_res_map_level_object_patch_item_key {
    uint32_t code;
} yc_res_map_level_object_patch_item_key_t;

#endif //LIBYCRES_INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_KEY_H
