#ifndef INCLUDE_PRO_TYPES_OBJECT_CRITTER_BODY_H
#define INCLUDE_PRO_TYPES_OBJECT_CRITTER_BODY_H

typedef enum yc_res_pro_object_critter_body {
    YC_RES_PRO_OBJECT_CRITTER_BODY_TYPE_BIPED,
    YC_RES_PRO_OBJECT_CRITTER_BODY_TYPE_QUADRUPED,
    YC_RES_PRO_OBJECT_CRITTER_BODY_TYPE_ROBOTIC,
} yc_res_pro_object_critter_body_t;

#endif //INCLUDE_PRO_TYPES_OBJECT_CRITTER_BODY_H
