#ifndef LIB_YCRES_PRO_TYPES_COMMON_CALIBER_H
#define LIB_YCRES_PRO_TYPES_COMMON_CALIBER_H

typedef enum yc_res_pro_caliber {
    YC_RES_PRO_CALIBER_TYPE_NONE,
    YC_RES_PRO_CALIBER_TYPE_ROCKET,
    YC_RES_PRO_CALIBER_TYPE_FLAMETHROWER_FUEL,
    YC_RES_PRO_CALIBER_TYPE_C_ENERGY_CELL,
    YC_RES_PRO_CALIBER_TYPE_D_ENERGY_CELL,
    YC_RES_PRO_CALIBER_TYPE_223,
    YC_RES_PRO_CALIBER_TYPE_5_MM,
    YC_RES_PRO_CALIBER_TYPE_40_CAL,
    YC_RES_PRO_CALIBER_TYPE_10_MM,
    YC_RES_PRO_CALIBER_TYPE_44_CAL,
    YC_RES_PRO_CALIBER_TYPE_14_MM,
    YC_RES_PRO_CALIBER_TYPE_12_GAUGE,
    YC_RES_PRO_CALIBER_TYPE_9_MM,
    YC_RES_PRO_CALIBER_TYPE_BB
} yc_res_pro_caliber_t;

#endif //LIB_YCRES_PRO_TYPES_COMMON_CALIBER_H
