#ifndef LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_H
#define LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_H

typedef struct yc_res_map_level_object_patch_scenery {
    yc_res_pro_object_scenery_type_t type;
} yc_res_map_level_object_patch_scenery_t;

#endif //LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_H
