#ifndef LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_CRITTER_H
#define LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_CRITTER_H

typedef struct yc_res_map_level_object_patch_critter {
    uint32_t packet_id;
} yc_res_map_level_object_patch_critter_t;

#endif //LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_CRITTER_H
