#ifndef INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_MISC_H
#define INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_MISC_H

typedef struct yc_res_map_level_object_patch_item_misc {
    uint32_t count;
} yc_res_map_level_object_patch_item_misc_t;

#endif //INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_MISC_H
