#ifndef LIB_YCRES_PRO_TYPES_ENTITY_H
#define LIB_YCRES_PRO_TYPES_ENTITY_H

typedef enum yc_res_entity {
    YC_RES_PRO_ENTITY_ITEM = 0,
    YC_RES_PRO_ENTITY_CRITTER,
    YC_RES_PRO_ENTITY_SCENERY,
    YC_RES_PRO_ENTITY_WALL,
    YC_RES_PRO_ENTITY_TILE,
    YC_RES_PRO_ENTITY_MISC,
    YC_RES_PRO_ENTITY_INTERFACE,
    YC_RES_PRO_ENTITY_INVENTORY,
    YC_RES_PRO_ENTITY_HEAD,
    YC_RES_PRO_ENTITY_BACKGROUND
} yc_res_entity_t;

#endif //LIB_YCRES_PRO_TYPES_ENTITY_H
