#ifndef LIBYCRES_INCLUDE_PRO_TYPES_OBJECT_SCENERY_LADDER_H
#define LIBYCRES_INCLUDE_PRO_TYPES_OBJECT_SCENERY_LADDER_H

typedef struct yc_res_pro_object_scenery_ladder {
    yc_res_math_location_t destination;
} yc_res_pro_object_scenery_ladder_t;

#endif //LIBYCRES_INCLUDE_PRO_TYPES_OBJECT_SCENERY_LADDER_H
