#ifndef LIB_YCRES_PRO_TYPES_OBJECT_SCENERY_LADDER_H
#define LIB_YCRES_PRO_TYPES_OBJECT_SCENERY_LADDER_H

typedef struct yc_res_pro_object_scenery_ladder {
    yc_res_pro_destination_t destination;
} yc_res_pro_object_scenery_ladder_t;

#endif //LIB_YCRES_PRO_TYPES_OBJECT_SCENERY_LADDER_H
