#ifndef LIBYCRES_INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_AMMO_H
#define LIBYCRES_INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_AMMO_H

typedef struct yc_res_map_level_object_patch_item_ammo {
    uint32_t count;
} yc_res_map_level_object_patch_item_ammo_t;

#endif //LIBYCRES_INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_ITEM_AMMO_H
