#ifndef INCLUDE_PRO_TYPES_OBJECT_CRITTER_KILL_H
#define INCLUDE_PRO_TYPES_OBJECT_CRITTER_KILL_H

typedef enum yc_res_pro_object_critter_kill {
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_MAN,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_WOMAN,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_CHILD,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_SUPER_MUTANT,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_GHOUL,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_BRAHMIN,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_RADSCORPION,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_RAT,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_FLOATER,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_CENTAUR,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_ROBOT,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_DOG,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_MANTIS,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_DEATH_CLAW,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_PLANT,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_GECKO,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_ALIEN,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_GIANT_ANT,
    YC_RES_PRO_OBJECT_CRITTER_KILL_TYPE_BIG_BAD_BOSS,
} yc_res_pro_object_critter_kill_t;

#endif //INCLUDE_PRO_TYPES_OBJECT_CRITTER_KILL_H
