#ifndef INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_DOOR_H
#define INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_DOOR_H

typedef struct yc_res_map_level_object_patch_scenery_door {
    bool is_passable;
} yc_res_map_level_object_patch_scenery_door_t;

#endif //INCLUDE_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_DOOR_H
