#ifndef LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_DOOR_H
#define LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_DOOR_H

typedef struct yc_res_map_level_object_patch_scenery_door {
    bool is_passable;
} yc_res_map_level_object_patch_scenery_door_t;

#endif //LIB_YCRES_MAP_TYPES_LEVEL_OBJECT_PATCH_SCENERY_DOOR_H
