#ifndef LIB_YCRES_PRO_PARSE_OBJECT_DESTINATION_H
#define LIB_YCRES_PRO_PARSE_OBJECT_DESTINATION_H

void yc_res_pro_parse_object_destination(uint32_t raw, yc_res_math_location_t *into);

#endif //LIB_YCRES_PRO_PARSE_OBJECT_DESTINATION_H
