#ifndef LIB_YCRES_PRO_TYPES_OBJECT_ITEM_ATTACKS_H
#define LIB_YCRES_PRO_TYPES_OBJECT_ITEM_ATTACKS_H

typedef enum yc_res_pro_object_item_attack {
    YC_RES_PRO_OBJECT_ITEM_ATTACK_NONE = 0,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_PUNCH,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_KICK,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_SWING,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_THRUST,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_THROW,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_FIRE_SINGLE,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_FIRE_BURST,
    YC_RES_PRO_OBJECT_ITEM_ATTACK_FLAME
} yc_res_pro_object_item_attack_t;

#endif //LIB_YCRES_PRO_TYPES_OBJECT_ITEM_ATTACKS_H
