#ifndef LIBYCRES_INCLUDE_PRO_TYPES_OBJECT_SCENERY_GENERIC_H
#define LIBYCRES_INCLUDE_PRO_TYPES_OBJECT_SCENERY_GENERIC_H

typedef struct yc_res_pro_object_scenery_generic {
    uint32_t unknown;
} yc_res_pro_object_scenery_generic_t;

#endif //LIBYCRES_INCLUDE_PRO_TYPES_OBJECT_SCENERY_GENERIC_H
