#ifndef LIB_YCRES_PRO_TYPES_OBJECT_ITEM_CONTAINER_FLAGS_H
#define LIB_YCRES_PRO_TYPES_OBJECT_ITEM_CONTAINER_FLAGS_H

typedef struct yc_res_pro_object_item_container_flags {
    bool no_pickup, is_grounded;
} yc_res_pro_object_item_container_flags_t;

#endif //LIB_YCRES_PRO_TYPES_OBJECT_ITEM_CONTAINER_FLAGS_H
