name: Valgrind
on:
  push:
  pull_request:
jobs:
  valgrind:
    name: Valgrind
    uses: steinwurf/valgrind-action/.github/workflows/action.yml@5.0.0
    with:
      extra_resolve_options: ${{ github.events.inputs.extra_resolve_options }}
